{
 "title": "Magpie Network Benchmarking",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "iperf client bandwidth (total)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(magpie_iperf_bandwidth[30s]))",
     "legendFormat": "bandwidth"
    }
   ]
  },
  {
   "title": "iperf bandwidth (unit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "avg_over_time(magpie_iperf_bandwidth[600s])",
     "legendFormat": "{{src}} -> {{dest}}"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total[5m]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "magpie_iperf_concurrency", "legendFormat": "{{src}} -> {{dest}}" }
   ]
  }
 ]
}