options:
  check_bonds:
    default: AUTO
    description: Comma separated list of expected bonds or AUTO to check all available bonds.
    type: string
  use_lldp:
    default: false
    description: Enable LLDP agent and collect data
    type: boolean
  check_port_description:
    default: false
    description: Check LLDP port description to match hostname
    type: boolean
  check_iperf:
    default: true
    description: Execute iperf network performance test
    type: boolean
  check_dns:
    default: true
    description: Check if peers are resolveble
    type: boolean
  check_local_hostname:
    default: true
    description: Check if local hostname is resolvable
    type: boolean
  dns_server:
    default: ''
    description: Use unit default DNS server
    type: string
  dns_tries:
    default: 1
    description: Number of DNS resolution attempts per query
    type: int
  dns_time:
    default: 3
    description: Timeout in seconds per DNS query try
    type: int
  ping_timeout:
    default: 2
    description: Timeout in seconds per ICMP request
    type: int
  ping_tries:
    default: 20
    description: Number of ICMP packets per ping
    type: int
  ping_interval:
    default: 0.05
    description: Number of seconds to wait between sending each packet
    type: float
  supress_status:
    default: False
    description: Enable this if you intend to consume this layer - suppresses status messages
    type: boolean
  required_mtu:
    default: 0
    description: Desired MTU for all nodes - block if the unit MTU is different (accounting for encapsulation). 0 disables.
    type: int
  min_speed:
    default: 0
    description: Minimum transfer speed in mbit/s required to pass the test. 0 disables.
    type: int
  iperf_duration:
    default: 1
    description: |
      Time in seconds to run iperf to test the transfer speed. Larger
      value can be set to mitigate the impact of CPU power saving
      features especially on faster links such as 50G.
    type: int
  source:
    default: distro
    type: string
    description: |
      Repository to add to unit before installing any dependencies.

      May be one of the following:

        distro (default)
        ppa:somecustom/ppa (PPA name must include UCA OpenStack Release name)
        deb url sources entry|key id
        or a supported Ubuntu Cloud Archive pocket.
